### ISSUE TITLE
bugs when use pytorch

### ISSUE THREAD

**Issue by tzjtatata** [google/python-fire#206]
Traceback (most recent call last):
  File "multilabel/runners/resnet_runner.py", line 26, in <module>
    main()
  File "multilabel/runners/resnet_runner.py", line 22, in main
    fire.Fire(resnet50)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 560, in _Fire
    treatment='callable')
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'x'

When I rewrite pytorch nn.Module, I use x as params to override forward function. This bugs appear.
I have test. If I do not use Fire, it works well.
I suppose that because fire did not support this kind of override? Or someone can tell me how to fix it.
Thanks.

**Comment by dbieber** [comment]
Could you provide the code for defining the resnet50 object in resnet_runner.py?
