### ISSUE TITLE
AttributeError: module 'ctypes' has no attribute 'wintypes'

### ISSUE THREAD

**Issue by HoBeom** [google/python-fire#269]
## import error in conda CMD.exe
```
(tf2) D:\PycharmProjects\tf2-upgraded>python main.py VP
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import fire
  File "C:\Anaconda3\envs\tf2\lib\site-packages\fire\__init__.py", line 21, in <module>
    from fire.core import Fire
  File "C:\Anaconda3\envs\tf2\lib\site-packages\fire\core.py", line 67, in <module>
    from fire import formatting
  File "C:\Anaconda3\envs\tf2\lib\site-packages\fire\formatting.py", line 21, in <module>
    from fire import formatting_windows  # pylint: disable=unused-import
  File "C:\Anaconda3\envs\tf2\lib\site-packages\fire\formatting_windows.py", line 60, in <module>
    initialize_or_disable()
  File "C:\Anaconda3\envs\tf2\lib\site-packages\fire\formatting_windows.py", line 47, in initialize_or_disable
    mode = ctypes.wintypes.DWORD()
AttributeError: module 'ctypes' has no attribute 'wintypes'
```
## import error in conda powershell
```
PS D:\PycharmProjects\tf2-upgraded> conda activate tf2
PS D:\PycharmProjects\tf2-upgraded> python main.py VP
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import fire
  File "C:\Anaconda3\lib\site-packages\fire\__init__.py", line 21, in <module>
    from fire.core import Fire
  File "C:\Anaconda3\lib\site-packages\fire\core.py", line 67, in <module>
    from fire import formatting
  File "C:\Anaconda3\lib\site-packages\fire\formatting.py", line 22, in <module>
    import termcolor
ModuleNotFoundError: No module named 'termcolor'
```
## My env is window10 anaconda python 
```
(tf2) D:\PycharmProjects\tf2-upgraded>conda list
# packages in environment at C:\Anaconda3\envs\tf2:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu
absl-py                   0.9.0                    py37_0
astor                     0.8.0                    py37_0
blas                      1.0                         mkl
blinker                   1.4                      py37_0
ca-certificates           2020.1.1                      0
cachetools                3.1.1                      py_0
certifi                   2020.4.5.1               py37_0
cffi                      1.14.0           py37h7a1dbc1_0
chardet                   3.0.4                 py37_1003
click                     7.1.2                      py_0
cryptography              2.9.2            py37h7a1dbc1_0
cudatoolkit               10.1.243             h74a9793_0
cudnn                     7.6.5                cuda10.1_0
fire                      0.3.1                    pypi_0    pypi
freetype                  2.9.1                ha9979f8_1
gast                      0.2.2                    py37_0
google-auth               1.14.1                     py_0
google-auth-oauthlib      0.4.1                      py_2
google-pasta              0.2.0                      py_0
grpcio                    1.27.2           py37h351948d_0
h5py                      2.10.0           py37h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
idna                      2.9                        py_1
intel-openmp              2020.1                      216
joblib                    0.15.1                   pypi_0    pypi
jpeg                      9b                   hb83a4c4_2
keras-applications        1.0.8                      py_0
keras-preprocessing       1.1.0                      py_1
libpng                    1.6.37               h2a8f88b_0
libprotobuf               3.11.4               h7bd577a_0
libtiff                   4.1.0                h56a325e_1
lz4-c                     1.9.2                h62dcd97_0
markdown                  3.1.1                    py37_0
mkl                       2020.1                      216
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.15           py37h14836fe_0
mkl_random                1.1.1            py37h47e9c7a_0
numpy                     1.18.1           py37h93ca92e_0
numpy-base                1.18.1           py37hc3f5095_1
oauthlib                  3.1.0                      py_0
olefile                   0.46                     py37_0
openssl                   1.1.1g               he774522_0
opt_einsum                3.1.0                      py_0
pillow                    7.1.2            py37hcc1f983_0
pip                       20.0.2                   py37_3
prdc                      0.2                      pypi_0    pypi
protobuf                  3.11.4           py37h33f27b4_0
pyasn1                    0.4.8                      py_0
pyasn1-modules            0.2.7                      py_0
pycparser                 2.20                       py_0
pyjwt                     1.7.1                    py37_0
pyopenssl                 19.1.0                   py37_0
pyreadline                2.1                      py37_1
pysocks                   1.7.1                    py37_0
python                    3.7.7                h81c818b_4
requests                  2.23.0                   py37_0
requests-oauthlib         1.3.0                      py_0
rsa                       4.0                        py_0
scikit-learn              0.23.1                   pypi_0    pypi
scipy                     1.4.1            py37h9439919_0
setuptools                46.4.0                   py37_0
six                       1.14.0                   py37_0
sqlite                    3.31.1               h2a8f88b_1
tensorboard               2.2.1              pyh532a8cf_0
tensorboard-plugin-wit    1.6.0                      py_0
tensorflow                2.1.0           gpu_py37h7db9008_0
tensorflow-base           2.1.0           gpu_py37h55f5790_0
tensorflow-estimator      2.1.0              pyhd54b08b_0
tensorflow-gpu            2.1.0                h0d30ee6_0
termcolor                 1.1.0                    py37_1
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.8                hfa6e2cd_0
urllib3                   1.25.8                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_2
werkzeug                  0.16.1                     py_0
wheel                     0.34.2                   py37_0
win_inet_pton             1.1.0                    py37_0
wincertstore              0.2                      py37_0
wrapt                     1.12.1           py37he774522_1
xz                        5.2.5                h62dcd97_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.4                ha9fde0e_3
```
## before I got error, I installed [prdc](https://github.com/clovaai/generative-evaluation-prdc).

**Comment by 1MLightyears** [comment]
Sorry I failed reproduce your problem at both Anaconda(version 2020.02) with Python 3.7.6 at Win10 and Python 3.6.9 at WSL.
Both "import termcolor" succeed and prdc is installed by pip.
Maybe something is wrong with your Anaconda?
(That is very likely to be the truth, since I have just broken my Anaconda today by "conda upgrade conda".)
