### ISSUE TITLE
Installing on Linux Mint 20 Ulyana

### ISSUE THREAD

**Issue by stanescuUW** [google/python-fire#271]
Having trouble installing this under Linux Mint 20, although it used to work under 19.3. Below are the error messages I get. Help will be greatly appreciated. I tried several python versions and all give me the same errors.

When installing with pip:
------------------------------------

pip3 install fire
Collecting fire
  Using cached fire-0.3.1.tar.gz (81 kB)
Requirement already satisfied: six in /home/dan/.virtualenvs/lean-game/lib/python3.8/site-packages (from fire) (1.14.0)
Collecting termcolor
  Using cached termcolor-1.1.0.tar.gz (3.9 kB)
Building wheels for collected packages: fire, termcolor
  Building wheel for fire (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/dan/.virtualenvs/lean-game/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1uxkgcwx/fire/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1uxkgcwx/fire/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-1tdzu9ip
       cwd: /tmp/pip-install-1uxkgcwx/fire/
  Complete output (92 lines):
  running bdist_wheel
  The [wheel] section is deprecated. Use [bdist_wheel] instead.
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/fire
  copying fire/parser_fuzz_test.py -> build/lib/fire
  copying fire/__init__.py -> build/lib/fire
  copying fire/test_components_test.py -> build/lib/fire
  copying fire/inspectutils_test.py -> build/lib/fire
  copying fire/helptext.py -> build/lib/fire
  copying fire/trace_test.py -> build/lib/fire
  copying fire/custom_descriptions.py -> build/lib/fire
  copying fire/inspectutils.py -> build/lib/fire
  copying fire/test_components_py3.py -> build/lib/fire
  copying fire/test_components_bin.py -> build/lib/fire
  copying fire/fire_import_test.py -> build/lib/fire
  copying fire/core_test.py -> build/lib/fire
  copying fire/core.py -> build/lib/fire
  copying fire/parser_test.py -> build/lib/fire
  copying fire/value_types.py -> build/lib/fire
  copying fire/main_test.py -> build/lib/fire
  copying fire/parser.py -> build/lib/fire
  copying fire/docstrings_test.py -> build/lib/fire
  copying fire/completion_test.py -> build/lib/fire
  copying fire/fire_test.py -> build/lib/fire
  copying fire/docstrings.py -> build/lib/fire
  copying fire/completion.py -> build/lib/fire
  copying fire/decorators_test.py -> build/lib/fire
  copying fire/decorators.py -> build/lib/fire
  copying fire/formatting_windows.py -> build/lib/fire
  copying fire/__main__.py -> build/lib/fire
  copying fire/test_components.py -> build/lib/fire
  copying fire/testutils.py -> build/lib/fire
  copying fire/testutils_test.py -> build/lib/fire
  copying fire/formatting.py -> build/lib/fire
  copying fire/trace.py -> build/lib/fire
  copying fire/helptext_test.py -> build/lib/fire
  copying fire/interact.py -> build/lib/fire
  copying fire/custom_descriptions_test.py -> build/lib/fire
  copying fire/formatting_test.py -> build/lib/fire
  copying fire/docstrings_fuzz_test.py -> build/lib/fire
  copying fire/interact_test.py -> build/lib/fire
  creating build/lib/fire/console
  copying fire/console/__init__.py -> build/lib/fire/console
  copying fire/console/console_pager.py -> build/lib/fire/console
  copying fire/console/console_attr_os.py -> build/lib/fire/console
  copying fire/console/encoding.py -> build/lib/fire/console
  copying fire/console/platforms.py -> build/lib/fire/console
  copying fire/console/files.py -> build/lib/fire/console
  copying fire/console/text.py -> build/lib/fire/console
  copying fire/console/console_attr.py -> build/lib/fire/console
  copying fire/console/console_io.py -> build/lib/fire/console
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-1uxkgcwx/fire/setup.py", line 46, in <module>
      setup(
    File "/home/dan/.virtualenvs/lean-game/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/dan/.virtualenvs/lean-game/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 259, in run
      self.run_command('install')
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/dan/.virtualenvs/lean-game/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
      return orig.install.run(self)
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/command/install.py", line 557, in run
      self.run_command(cmd_name)
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/dist.py", line 984, in run_command
      cmd_obj.ensure_finalized()
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
      self.finalize_options()
    File "/home/dan/.virtualenvs/lean-game/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 17, in finalize_options
      self.set_undefined_options('install',('install_layout','install_layout'))
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/cmd.py", line 290, in set_undefined_options
      setattr(self, dst_option, getattr(src_cmd_obj, src_option))
    File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/cmd.py", line 103, in __getattr__
      raise AttributeError(attr)
  AttributeError: install_layout
  ----------------------------------------
  ERROR: Failed building wheel for fire

When trying to build:
--------------------------------------
python setup.py install
running install
Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    setup(
  File "/home/dan/.virtualenvs/lean-game/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/dan/.virtualenvs/lean-game/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/dan/.virtualenvs/lean-game/lib/python3.8/site-packages/setuptools/command/install.py", line 103, in do_egg_install
    cmd.ensure_finalized()  # finalize before bdist_egg munges install cmd
  File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/dan/.virtualenvs/lean-game/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 311, in finalize_options
    self.set_undefined_options(
  File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/cmd.py", line 287, in set_undefined_options
    src_cmd_obj.ensure_finalized()
  File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/dan/.virtualenvs/lean-game/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 17, in finalize_options
    self.set_undefined_options('install',('install_layout','install_layout'))
  File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/cmd.py", line 290, in set_undefined_options
    setattr(self, dst_option, getattr(src_cmd_obj, src_option))
  File "/home/dan/.pyenv/versions/3.8.3/lib/python3.8/distutils/cmd.py", line 103, in __getattr__
    raise AttributeError(attr)
AttributeError: install_layout

**Comment by dbieber** [comment]
https://stackoverflow.com/questions/36296134/attributeerror-install-layout-when-attempting-to-install-a-package-in-a-virtual suggests the error could be an out of date setuptools.
Try `pip install --upgrade setuptools` and then try installing Fire again.

**Comment by stanescuUW** [comment]
@dbieber Indeed, this was it! Thank you, issue closed.
