### ISSUE TITLE
expected string or bytes-like object

### ISSUE THREAD

**Issue by mastercho** [google/python-fire#386]
When i run install command

`pip3 install fire==0.4.0`

Getting error like

```
Collecting fire==0.4.0
  Using cached fire-0.4.0.tar.gz (87 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Ninja\AppData\Local\Temp\pip-install-t_sfjybp\fire_f0bc0f6cd5b548d09e6b955160ec2b94\setup.py", line 46, in <module>
          setup(
        File "C:\Python38\lib\site-packages\setuptools\__init__.py", line 154, in setup
          _install_setup_requires(attrs)
        File "C:\Python38\lib\site-packages\setuptools\__init__.py", line 143, in _install_setup_requires
          dist = MinimalDistribution(attrs)
        File "C:\Python38\lib\site-packages\setuptools\__init__.py", line 135, in __init__
          super().__init__(filtered)
        File "C:\Python38\lib\site-packages\setuptools\dist.py", line 456, in __init__
          for ep in metadata.entry_points(group='distutils.setup_keywords'):
        File "C:\Python38\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 999, in entry_points
          return SelectableGroups.load(eps).select(**params)
        File "C:\Python38\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 449, in load
          ordered = sorted(eps, key=by_group)
        File "C:\Python38\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 996, in <genexpr>
          eps = itertools.chain.from_iterable(
        File "C:\Python38\lib\site-packages\setuptools\_vendor\importlib_metadata\_itertools.py", line 16, in unique_everseen
          k = key(element)
        File "C:\Python38\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 931, in _normalized_name
          return self._name_from_stem(stem) or super()._normalized_name
        File "C:\Python38\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 600, in _normalized_name
          return Prepared.normalize(self.name)
        File "C:\Python38\lib\site-packages\setuptools\_vendor\importlib_metadata\__init__.py", line 855, in normalize
          return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
        File "C:\Python38\lib\re.py", line 208, in sub
          return _compile(pattern, flags).sub(repl, string, count)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

Any suggestions why version 4 throws that? 

`pip3 install fire` installs 0.3.1 for me

**Comment by alecgarza96** [comment]
What environment are you on? I wasn't able to recreate on windows

**Comment by alecgarza96** [comment]
Did some research and found users facing similar issues here

https://stackoverflow.com/questions/71009659/note-this-error-originates-from-a-subprocess-and-is-likely-not-a-problem-with

https://github.com/claws/buildbot-prometheus/issues/13

https://github.com/mkleehammer/pyodbc/issues/981

It appears this could be related to python versions and windows environments

**Comment by dbieber** [comment]
I'm going to close this since it doesn't appear to be a fire related issue.
Please do share the resolution if you find it though.
