### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PY34'

### ISSUE THREAD

**Issue by FANGOD** [google/python-fire#474]
```
Traceback (most recent call last):
  File "deploy.py", line 12, in <module>
    import fire
  File "/home/gitlab-runner/.local/lib/python2.7/site-packages/fire/__init__.py", line 21, in <module>
    from fire.core import Fire
  File "/home/gitlab-runner/.local/lib/python2.7/site-packages/fire/core.py", line 65, in <module>
    from fire import completion
  File "/home/gitlab-runner/.local/lib/python2.7/site-packages/fire/completion.py", line 25, in <module>
    from fire import inspectutils
  File "/home/gitlab-runner/.local/lib/python2.7/site-packages/fire/inspectutils.py", line 29, in <module>
    if six.PY34:
AttributeError: 'module' object has no attribute 'PY34'
```

python2.7.5

**Comment by dbieber** [comment]
Looks like https://github.com/docker/docker-py/issues/2294#issuecomment-486269556 might be the issue here
