### ISSUE TITLE
unable to install fire

### ISSUE THREAD

**Issue by brenscar2020** [google/python-fire#486]
Hi,

I have getting the error below when attempting to install fire. 

└─$ python3 setup.py install
Traceback (most recent call last):
  File "/home/kali/python-fire/setup.py", line 46, in <module>
    setup(
  File "/home/kali/.local/lib/python3.11/site-packages/setuptools/__init__.py", line 102, in setup
    _install_setup_requires(attrs)
  File "/home/kali/.local/lib/python3.11/site-packages/setuptools/__init__.py", line 70, in _install_setup_requires
    dist = MinimalDistribution(attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/setuptools/__init__.py", line 52, in __init__
    super().__init__(filtered)
  File "/home/kali/.local/lib/python3.11/site-packages/setuptools/dist.py", line 297, in __init__
    for ep in metadata.entry_points(group='distutils.setup_keywords'):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 1040, in entry_points
    return SelectableGroups.load(eps).select(**params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 476, in load
    ordered = sorted(eps, key=by_group)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 1037, in <genexpr>
    eps = itertools.chain.from_iterable(
                                       ^
  File "/usr/lib/python3.11/importlib/metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
        ^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 954, in _normalized_name
    or super()._normalized_name
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 627, in _normalized_name
    return Prepared.normalize(self.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 882, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

I've tried installing using "pip install", I've tried downloading the latest version directly from https://pypi.org/project/fire/#files, and tried using pip to install that, and I've tried cloning the repository and installing it that way. But no method is working for me.

I've looked through the issues here on github and the Installation page, but can't find any resolutions.

Can you advise on how I might be able to resolve this please? 

Thanks

**Comment by dbieber** [comment]
Thanks for reporting. Does installing other packages work for you?

**Comment by brenscar2020** [comment]
yes, I can install other packages fine

**Comment by dbieber** [comment]
There's a new version (v0.6.0) on pypi. I don't know that it would make a difference here, but try installing again and lmk.
Going forward we're going to switch to pyproject.toml, so if you're issue isn't already resolved w 0.6.0 it's possible it will be resolved by that next upcoming change.

**Comment by dbieber** [comment]
Closing. Feel free to reopen or add info as needed.
